# Generated by Django 4.1.2 on 2022-11-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="conclusion_datetime",
            field=models.DateTimeField(null=True),
        ),
    ]
