# Generated by Django 4.1.2 on 2022-11-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_recipe_conclusion_datetime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="conclusion_datetime",
        ),
        migrations.AddField(
            model_name="recipe",
            name="conclusion_date",
            field=models.DateField(null=True),
        ),
    ]
